[project]
name = "energy-dashboard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["pandas>=2.3.1", "psycopg>=3.2.9", "requests>=2.32.4"]
